source 'https://rubygems.org'

gem 'cld2'
gem 'colored'
gem 'faraday'
gem 'google-api-client'
gem 'hashdiff'
gem 'htmlentities'
gem 'mail'
gem 'netrc'
gem 'nokogiri'
# See https://github.com/octokit/octokit.rb/pull/978
gem 'octokit', git: 'https://github.com/jpmckinney/octokit.rb.git', branch: 'pr/977'
gem 'rake'
gem 'safe_yaml'
